version: "3"
services:
 web:
  build: .
  ports:
   - '4567:4567'
  networks:
   - external_network
   - internal_network
  depends_on:
   - mysql
  volumes:
   - ./config.properties:/usr/local/etc/config.properties
   - ./appmap-1.17.2.jar:/usr/src/app/appmap-1.17.2.jar
   - smithereen-media:/uploads
   - ./target:/usr/src/app/target
  restart: always
 mysql:
  image: amd64/mysql:8
  environment:
   MYSQL_ROOT_PASSWORD: smithereen
   MYSQL_DATABASE: smithereen
   MYSQL_INITDB_SKIP_TZINFO: 1
  networks:
   - internal_network
  healthcheck:
   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  volumes:
   - smithereen-mysql-data:/var/lib/mysql
   - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  restart: always
 imgproxy:
  image: darthsim/imgproxy:latest
  ports:
   - '4560:8080'
  environment:
   IMGPROXY_PATH_PREFIX: "/i"
   IMGPROXY_ALLOWED_SOURCES: "local://"
   IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/uploads"
   # See README or config_docker.properties for how to generate these.
   # Must match config, otherwise you won't be seeing any memes in the newsfeed.
   IMGPROXY_KEY: e35370575394e3cb3140bf37657f7f861b4ea2f79ca394191268b7f01fc4c0a9
   IMGPROXY_SALT: f398a7d4b1926924eee7d82d7f5dbf1f89b870ad23da2ed30353cf922a6c5827
  volumes:
   - smithereen-media:/uploads
  restart: always
  networks:
   - external_network

networks:
  external_network:
  internal_network:
    internal: true

volumes:
  smithereen-media:
  smithereen-mysql-data:
